# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devices.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_devices(object):
    def setupUi(self, devices):
        devices.setObjectName("devices")
        devices.resize(200, 230)
        devices.setStyleSheet("background-color: rgb(40,40,40)")
        self.centralWidget = QtWidgets.QWidget(devices)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 180, 195))
        self.groupBox.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lbl_main = QtWidgets.QLabel(self.groupBox)
        self.lbl_main.setGeometry(QtCore.QRect(40, 0, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_main.setFont(font)
        self.lbl_main.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lbl_main.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_main.setObjectName("lbl_main")
        self.zwo_btn = QtWidgets.QPushButton(self.groupBox)
        self.zwo_btn.setGeometry(QtCore.QRect(110, 30, 50, 20))
        self.zwo_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.zwo_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.zwo_btn.setFont(font)
        self.zwo_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.zwo_btn.setObjectName("zwo_btn")
        self.zwo_lbl = QtWidgets.QLabel(self.groupBox)
        self.zwo_lbl.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zwo_lbl.setFont(font)
        self.zwo_lbl.setStyleSheet("")
        self.zwo_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zwo_lbl.setObjectName("zwo_lbl")
        self.qhy_btn = QtWidgets.QPushButton(self.groupBox)
        self.qhy_btn.setGeometry(QtCore.QRect(110, 60, 50, 20))
        self.qhy_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.qhy_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.qhy_btn.setFont(font)
        self.qhy_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.qhy_btn.setObjectName("qhy_btn")
        self.qhy_lbl = QtWidgets.QLabel(self.groupBox)
        self.qhy_lbl.setGeometry(QtCore.QRect(10, 60, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.qhy_lbl.setFont(font)
        self.qhy_lbl.setStyleSheet("")
        self.qhy_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qhy_lbl.setObjectName("qhy_lbl")
        self.stage_btn = QtWidgets.QPushButton(self.groupBox)
        self.stage_btn.setGeometry(QtCore.QRect(110, 90, 50, 20))
        self.stage_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.stage_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stage_btn.setFont(font)
        self.stage_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.stage_btn.setObjectName("stage_btn")
        self.stage_lbl = QtWidgets.QLabel(self.groupBox)
        self.stage_lbl.setGeometry(QtCore.QRect(10, 90, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stage_lbl.setFont(font)
        self.stage_lbl.setStyleSheet("")
        self.stage_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stage_lbl.setObjectName("stage_lbl")
        self.adc_btn = QtWidgets.QPushButton(self.groupBox)
        self.adc_btn.setGeometry(QtCore.QRect(110, 120, 50, 20))
        self.adc_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.adc_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.adc_btn.setFont(font)
        self.adc_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.adc_btn.setObjectName("adc_btn")
        self.adc_lbl = QtWidgets.QLabel(self.groupBox)
        self.adc_lbl.setGeometry(QtCore.QRect(10, 120, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.adc_lbl.setFont(font)
        self.adc_lbl.setStyleSheet("")
        self.adc_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adc_lbl.setObjectName("adc_lbl")
        self.ref_btn = QtWidgets.QPushButton(self.groupBox)
        self.ref_btn.setGeometry(QtCore.QRect(110, 150, 50, 20))
        self.ref_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.ref_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ref_btn.setFont(font)
        self.ref_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.ref_btn.setObjectName("ref_btn")
        self.ref_lbl = QtWidgets.QLabel(self.groupBox)
        self.ref_lbl.setGeometry(QtCore.QRect(10, 150, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ref_lbl.setFont(font)
        self.ref_lbl.setStyleSheet("")
        self.ref_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ref_lbl.setObjectName("ref_lbl")
        devices.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(devices)
        self.statusBar.setObjectName("statusBar")
        devices.setStatusBar(self.statusBar)

        self.retranslateUi(devices)
        QtCore.QMetaObject.connectSlotsByName(devices)

    def retranslateUi(self, devices):
        _translate = QtCore.QCoreApplication.translate
        devices.setWindowTitle(_translate("devices", "devices"))
        self.lbl_main.setText(_translate("devices", "Device Control"))
        self.zwo_btn.setText(_translate("devices", "Enabled"))
        self.zwo_lbl.setText(_translate("devices", "ZWO Camera:"))
        self.qhy_btn.setText(_translate("devices", "Disabled"))
        self.qhy_lbl.setText(_translate("devices", "QHY Filter wheel:"))
        self.stage_btn.setText(_translate("devices", "Enabled"))
        self.stage_lbl.setText(_translate("devices", "Stage:"))
        self.adc_btn.setText(_translate("devices", "Enabled"))
        self.adc_lbl.setText(_translate("devices", "ADC:"))
        self.ref_btn.setText(_translate("devices", "Enabled"))
        self.ref_lbl.setText(_translate("devices", "Refractor Camera:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    devices = QtWidgets.QMainWindow()
    ui = Ui_devices()
    ui.setupUi(devices)
    devices.show()
    sys.exit(app.exec_())
