# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fhireGUI10.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 740)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 740))
        MainWindow.setMaximumSize(QtCore.QSize(1122, 747))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(0,0,0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(1080, 700))
        self.groupBox_8.setMaximumSize(QtCore.QSize(1080, 700))
        self.groupBox_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 420, 630, 260))
        self.groupBox_2.setMinimumSize(QtCore.QSize(630, 260))
        self.groupBox_2.setMaximumSize(QtCore.QSize(630, 260))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.terminal_edit = QtWidgets.QTextEdit(self.groupBox_2)
        self.terminal_edit.setGeometry(QtCore.QRect(0, 0, 350, 210))
        self.terminal_edit.setMinimumSize(QtCore.QSize(350, 210))
        self.terminal_edit.setMaximumSize(QtCore.QSize(350, 210))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.terminal_edit.setFont(font)
        self.terminal_edit.setStyleSheet("background-color: rgb(255,255,255);")
        self.terminal_edit.setObjectName("terminal_edit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 210, 640, 70))
        self.groupBox_6.setMinimumSize(QtCore.QSize(640, 70))
        self.groupBox_6.setMaximumSize(QtCore.QSize(640, 70))
        self.groupBox_6.setStyleSheet("::title {color: rgb(255,255,255)}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.claudius_lbl1 = QtWidgets.QLabel(self.groupBox_6)
        self.claudius_lbl1.setGeometry(QtCore.QRect(0, 20, 31, 25))
        self.claudius_lbl1.setMinimumSize(QtCore.QSize(0, 25))
        self.claudius_lbl1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.claudius_lbl1.setStyleSheet("color: rgb(255,255,255)")
        self.claudius_lbl1.setObjectName("claudius_lbl1")
        self.claudius_command_lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.claudius_command_lineEdit.setGeometry(QtCore.QRect(40, 20, 260, 25))
        self.claudius_command_lineEdit.setMinimumSize(QtCore.QSize(260, 25))
        self.claudius_command_lineEdit.setMaximumSize(QtCore.QSize(260, 25))
        self.claudius_command_lineEdit.setStyleSheet("background-color: rgb(255,255,255)")
        self.claudius_command_lineEdit.setText("")
        self.claudius_command_lineEdit.setObjectName("claudius_command_lineEdit")
        self.claudius_lbl2 = QtWidgets.QLabel(self.groupBox_6)
        self.claudius_lbl2.setGeometry(QtCore.QRect(310, 10, 320, 40))
        self.claudius_lbl2.setMinimumSize(QtCore.QSize(320, 40))
        self.claudius_lbl2.setMaximumSize(QtCore.QSize(320, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.claudius_lbl2.setFont(font)
        self.claudius_lbl2.setStyleSheet("color: rgb(0, 255, 0)")
        self.claudius_lbl2.setObjectName("claudius_lbl2")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_17.setGeometry(QtCore.QRect(360, 0, 270, 210))
        self.groupBox_17.setMinimumSize(QtCore.QSize(270, 210))
        self.groupBox_17.setMaximumSize(QtCore.QSize(270, 210))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_17.setObjectName("groupBox_17")
        self.centroid_lbl = QtWidgets.QLabel(self.groupBox_17)
        self.centroid_lbl.setGeometry(QtCore.QRect(30, 80, 55, 20))
        self.centroid_lbl.setMinimumSize(QtCore.QSize(55, 20))
        self.centroid_lbl.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.centroid_lbl.setFont(font)
        self.centroid_lbl.setObjectName("centroid_lbl")
        self.printcen_btn = QtWidgets.QPushButton(self.groupBox_17)
        self.printcen_btn.setGeometry(QtCore.QRect(30, 30, 130, 30))
        self.printcen_btn.setMinimumSize(QtCore.QSize(130, 30))
        self.printcen_btn.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printcen_btn.setFont(font)
        self.printcen_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.printcen_btn.setObjectName("printcen_btn")
        self.move_lbl = QtWidgets.QLabel(self.groupBox_17)
        self.move_lbl.setGeometry(QtCore.QRect(130, 80, 40, 20))
        self.move_lbl.setMinimumSize(QtCore.QSize(40, 20))
        self.move_lbl.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.move_lbl.setFont(font)
        self.move_lbl.setObjectName("move_lbl")
        self.move_lbl_2 = QtWidgets.QLabel(self.groupBox_17)
        self.move_lbl_2.setGeometry(QtCore.QRect(180, 70, 75, 41))
        self.move_lbl_2.setMinimumSize(QtCore.QSize(50, 20))
        self.move_lbl_2.setMaximumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.move_lbl_2.setFont(font)
        self.move_lbl_2.setObjectName("move_lbl_2")
        self.move_btn = QtWidgets.QPushButton(self.groupBox_17)
        self.move_btn.setGeometry(QtCore.QRect(180, 30, 60, 30))
        self.move_btn.setMinimumSize(QtCore.QSize(60, 30))
        self.move_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.move_btn.setFont(font)
        self.move_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.move_btn.setObjectName("move_btn")
        self.auto_on_rdb = QtWidgets.QRadioButton(self.groupBox_17)
        self.auto_on_rdb.setGeometry(QtCore.QRect(130, 110, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.auto_on_rdb.setFont(font)
        self.auto_on_rdb.setObjectName("auto_on_rdb")
        self.auto_off_rdb = QtWidgets.QRadioButton(self.groupBox_17)
        self.auto_off_rdb.setGeometry(QtCore.QRect(200, 110, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.auto_off_rdb.setFont(font)
        self.auto_off_rdb.setObjectName("auto_off_rdb")
        self.saving_on_rdb = QtWidgets.QRadioButton(self.groupBox_17)
        self.saving_on_rdb.setGeometry(QtCore.QRect(130, 160, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saving_on_rdb.setFont(font)
        self.saving_on_rdb.setObjectName("saving_on_rdb")
        self.saving_off_rdb = QtWidgets.QRadioButton(self.groupBox_17)
        self.saving_off_rdb.setGeometry(QtCore.QRect(200, 160, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saving_off_rdb.setFont(font)
        self.saving_off_rdb.setObjectName("saving_off_rdb")
        self.auto_lbl = QtWidgets.QLabel(self.groupBox_17)
        self.auto_lbl.setGeometry(QtCore.QRect(30, 110, 90, 30))
        self.auto_lbl.setMinimumSize(QtCore.QSize(90, 30))
        self.auto_lbl.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.auto_lbl.setFont(font)
        self.auto_lbl.setObjectName("auto_lbl")
        self.saving_lbl = QtWidgets.QLabel(self.groupBox_17)
        self.saving_lbl.setGeometry(QtCore.QRect(30, 150, 90, 40))
        self.saving_lbl.setMinimumSize(QtCore.QSize(90, 40))
        self.saving_lbl.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.saving_lbl.setFont(font)
        self.saving_lbl.setObjectName("saving_lbl")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_8)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 430, 700))
        self.tabWidget.setMinimumSize(QtCore.QSize(430, 700))
        self.tabWidget.setMaximumSize(QtCore.QSize(430, 700))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-right: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 420, 670))
        self.groupBox_4.setMinimumSize(QtCore.QSize(420, 670))
        self.groupBox_4.setMaximumSize(QtCore.QSize(420, 670))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(240, 390, 190, 275))
        self.groupBox_9.setMinimumSize(QtCore.QSize(190, 275))
        self.groupBox_9.setMaximumSize(QtCore.QSize(190, 275))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_9.setObjectName("groupBox_9")
        self.camera_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.camera_2.setGeometry(QtCore.QRect(10, 20, 160, 85))
        self.camera_2.setMinimumSize(QtCore.QSize(160, 85))
        self.camera_2.setMaximumSize(QtCore.QSize(160, 85))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.camera_2.setFont(font)
        self.camera_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.camera_2.setObjectName("camera_2")
        self.cfocus_btn_sub = QtWidgets.QPushButton(self.camera_2)
        self.cfocus_btn_sub.setGeometry(QtCore.QRect(10, 30, 20, 20))
        self.cfocus_btn_sub.setMinimumSize(QtCore.QSize(20, 20))
        self.cfocus_btn_sub.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_btn_sub.setFont(font)
        self.cfocus_btn_sub.setObjectName("cfocus_btn_sub")
        self.cfocus_btn_add = QtWidgets.QPushButton(self.camera_2)
        self.cfocus_btn_add.setGeometry(QtCore.QRect(130, 30, 20, 20))
        self.cfocus_btn_add.setMinimumSize(QtCore.QSize(20, 20))
        self.cfocus_btn_add.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_btn_add.setFont(font)
        self.cfocus_btn_add.setObjectName("cfocus_btn_add")
        self.cfocus_lbl = QtWidgets.QLabel(self.camera_2)
        self.cfocus_lbl.setGeometry(QtCore.QRect(30, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cfocus_lbl.setFont(font)
        self.cfocus_lbl.setStyleSheet("")
        self.cfocus_lbl.setObjectName("cfocus_lbl")
        self.cfocus_count = QtWidgets.QLabel(self.camera_2)
        self.cfocus_count.setGeometry(QtCore.QRect(90, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_count.setFont(font)
        self.cfocus_count.setStyleSheet("")
        self.cfocus_count.setObjectName("cfocus_count")
        self.cfocus_lineEdit = QtWidgets.QLineEdit(self.camera_2)
        self.cfocus_lineEdit.setGeometry(QtCore.QRect(40, 30, 40, 20))
        self.cfocus_lineEdit.setMinimumSize(QtCore.QSize(40, 20))
        self.cfocus_lineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.cfocus_lineEdit.setStyleSheet("background-color: rgb(255,255,255);")
        self.cfocus_lineEdit.setObjectName("cfocus_lineEdit")
        self.cfocus_setbtn = QtWidgets.QPushButton(self.camera_2)
        self.cfocus_setbtn.setGeometry(QtCore.QRect(80, 30, 40, 20))
        self.cfocus_setbtn.setMinimumSize(QtCore.QSize(40, 20))
        self.cfocus_setbtn.setMaximumSize(QtCore.QSize(40, 20))
        self.cfocus_setbtn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.cfocus_setbtn.setObjectName("cfocus_setbtn")
        self.ADC_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.ADC_2.setGeometry(QtCore.QRect(10, 110, 160, 145))
        self.ADC_2.setMinimumSize(QtCore.QSize(160, 145))
        self.ADC_2.setMaximumSize(QtCore.QSize(160, 145))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ADC_2.setFont(font)
        self.ADC_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ADC_2.setObjectName("ADC_2")
        self.afocus1_btn_sub = QtWidgets.QPushButton(self.ADC_2)
        self.afocus1_btn_sub.setGeometry(QtCore.QRect(10, 30, 20, 20))
        self.afocus1_btn_sub.setMinimumSize(QtCore.QSize(20, 20))
        self.afocus1_btn_sub.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.afocus1_btn_sub.setFont(font)
        self.afocus1_btn_sub.setObjectName("afocus1_btn_sub")
        self.afocus1_btn_add = QtWidgets.QPushButton(self.ADC_2)
        self.afocus1_btn_add.setGeometry(QtCore.QRect(130, 30, 20, 20))
        self.afocus1_btn_add.setMinimumSize(QtCore.QSize(20, 20))
        self.afocus1_btn_add.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.afocus1_btn_add.setFont(font)
        self.afocus1_btn_add.setObjectName("afocus1_btn_add")
        self.afocus2_btn_sub = QtWidgets.QPushButton(self.ADC_2)
        self.afocus2_btn_sub.setGeometry(QtCore.QRect(10, 90, 20, 20))
        self.afocus2_btn_sub.setMinimumSize(QtCore.QSize(20, 20))
        self.afocus2_btn_sub.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.afocus2_btn_sub.setFont(font)
        self.afocus2_btn_sub.setObjectName("afocus2_btn_sub")
        self.afocus2_btn_add = QtWidgets.QPushButton(self.ADC_2)
        self.afocus2_btn_add.setGeometry(QtCore.QRect(130, 90, 20, 20))
        self.afocus2_btn_add.setMinimumSize(QtCore.QSize(20, 20))
        self.afocus2_btn_add.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.afocus2_btn_add.setFont(font)
        self.afocus2_btn_add.setObjectName("afocus2_btn_add")
        self.afocus1_count = QtWidgets.QLabel(self.ADC_2)
        self.afocus1_count.setGeometry(QtCore.QRect(90, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.afocus1_count.setFont(font)
        self.afocus1_count.setStyleSheet("")
        self.afocus1_count.setObjectName("afocus1_count")
        self.afocus1_lbl = QtWidgets.QLabel(self.ADC_2)
        self.afocus1_lbl.setGeometry(QtCore.QRect(30, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.afocus1_lbl.setFont(font)
        self.afocus1_lbl.setStyleSheet("")
        self.afocus1_lbl.setObjectName("afocus1_lbl")
        self.afocus2_lbl = QtWidgets.QLabel(self.ADC_2)
        self.afocus2_lbl.setGeometry(QtCore.QRect(30, 120, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.afocus2_lbl.setFont(font)
        self.afocus2_lbl.setStyleSheet("")
        self.afocus2_lbl.setObjectName("afocus2_lbl")
        self.afcous2_count = QtWidgets.QLabel(self.ADC_2)
        self.afcous2_count.setGeometry(QtCore.QRect(90, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.afcous2_count.setFont(font)
        self.afcous2_count.setStyleSheet("")
        self.afcous2_count.setObjectName("afcous2_count")
        self.afocus1_lineEdit = QtWidgets.QLineEdit(self.ADC_2)
        self.afocus1_lineEdit.setGeometry(QtCore.QRect(40, 30, 40, 20))
        self.afocus1_lineEdit.setMinimumSize(QtCore.QSize(40, 20))
        self.afocus1_lineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.afocus1_lineEdit.setStyleSheet("background-color: rgb(255,255,255);")
        self.afocus1_lineEdit.setObjectName("afocus1_lineEdit")
        self.afocus2_lineEdit = QtWidgets.QLineEdit(self.ADC_2)
        self.afocus2_lineEdit.setGeometry(QtCore.QRect(40, 90, 40, 20))
        self.afocus2_lineEdit.setMinimumSize(QtCore.QSize(40, 20))
        self.afocus2_lineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.afocus2_lineEdit.setStyleSheet("background-color: rgb(255,255,255);")
        self.afocus2_lineEdit.setObjectName("afocus2_lineEdit")
        self.afocus1_setbtn = QtWidgets.QPushButton(self.ADC_2)
        self.afocus1_setbtn.setGeometry(QtCore.QRect(80, 30, 40, 20))
        self.afocus1_setbtn.setMinimumSize(QtCore.QSize(40, 20))
        self.afocus1_setbtn.setMaximumSize(QtCore.QSize(40, 20))
        self.afocus1_setbtn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.afocus1_setbtn.setObjectName("afocus1_setbtn")
        self.afocus2_setbtn = QtWidgets.QPushButton(self.ADC_2)
        self.afocus2_setbtn.setGeometry(QtCore.QRect(80, 90, 40, 20))
        self.afocus2_setbtn.setMinimumSize(QtCore.QSize(40, 20))
        self.afocus2_setbtn.setMaximumSize(QtCore.QSize(40, 20))
        self.afocus2_setbtn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.afocus2_setbtn.setObjectName("afocus2_setbtn")
        self.destination_path_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.destination_path_2.setGeometry(QtCore.QRect(0, 390, 235, 65))
        self.destination_path_2.setMinimumSize(QtCore.QSize(235, 65))
        self.destination_path_2.setMaximumSize(QtCore.QSize(235, 65))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.destination_path_2.setFont(font)
        self.destination_path_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.destination_path_2.setObjectName("destination_path_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.destination_path_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.dir_tool_btn_2 = QtWidgets.QToolButton(self.destination_path_2)
        self.dir_tool_btn_2.setMinimumSize(QtCore.QSize(0, 20))
        self.dir_tool_btn_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.dir_tool_btn_2.setObjectName("dir_tool_btn_2")
        self.gridLayout_29.addWidget(self.dir_tool_btn_2, 0, 2, 1, 1)
        self.dir_inp = QtWidgets.QLineEdit(self.destination_path_2)
        self.dir_inp.setMinimumSize(QtCore.QSize(0, 20))
        self.dir_inp.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dir_inp.setFont(font)
        self.dir_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dir_inp.setObjectName("dir_inp")
        self.gridLayout_29.addWidget(self.dir_inp, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 460, 235, 50))
        self.groupBox_10.setMinimumSize(QtCore.QSize(235, 50))
        self.groupBox_10.setMaximumSize(QtCore.QSize(235, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_10.setObjectName("groupBox_10")
        self.prefix_inp = QtWidgets.QLineEdit(self.groupBox_10)
        self.prefix_inp.setGeometry(QtCore.QRect(20, 20, 125, 20))
        self.prefix_inp.setMinimumSize(QtCore.QSize(125, 20))
        self.prefix_inp.setMaximumSize(QtCore.QSize(125, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prefix_inp.setFont(font)
        self.prefix_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.prefix_inp.setObjectName("prefix_inp")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 210, 430, 85))
        self.groupBox_11.setMinimumSize(QtCore.QSize(430, 85))
        self.groupBox_11.setMaximumSize(QtCore.QSize(430, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_11.setObjectName("groupBox_11")
        self.filter_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.filter_btn.setGeometry(QtCore.QRect(340, 30, 35, 35))
        self.filter_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.filter_btn.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filter_btn.setFont(font)
        self.filter_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.filter_btn.setObjectName("filter_btn")
        self.filter_ind = QtWidgets.QLabel(self.groupBox_11)
        self.filter_ind.setGeometry(QtCore.QRect(60, 20, 125, 50))
        self.filter_ind.setMinimumSize(QtCore.QSize(125, 50))
        self.filter_ind.setMaximumSize(QtCore.QSize(125, 50))
        self.filter_ind.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.filter_ind.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_ind.setObjectName("filter_ind")
        self.filter_cmb = QtWidgets.QComboBox(self.groupBox_11)
        self.filter_cmb.setGeometry(QtCore.QRect(210, 30, 115, 35))
        self.filter_cmb.setMinimumSize(QtCore.QSize(115, 35))
        self.filter_cmb.setMaximumSize(QtCore.QSize(115, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filter_cmb.setFont(font)
        self.filter_cmb.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(191, 191, 191);")
        self.filter_cmb.setObjectName("filter_cmb")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 300, 430, 85))
        self.groupBox_18.setMinimumSize(QtCore.QSize(430, 85))
        self.groupBox_18.setMaximumSize(QtCore.QSize(430, 85))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_18.setObjectName("groupBox_18")
        self.home_btn = QtWidgets.QPushButton(self.groupBox_18)
        self.home_btn.setGeometry(QtCore.QRect(20, 40, 100, 30))
        self.home_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.home_btn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.home_btn.setFont(font)
        self.home_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.home_btn.setObjectName("home_btn")
        self.mirror_btn = QtWidgets.QPushButton(self.groupBox_18)
        self.mirror_btn.setGeometry(QtCore.QRect(130, 40, 100, 30))
        self.mirror_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.mirror_btn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mirror_btn.setFont(font)
        self.mirror_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.mirror_btn.setObjectName("mirror_btn")
        self.splitter_btn = QtWidgets.QPushButton(self.groupBox_18)
        self.splitter_btn.setGeometry(QtCore.QRect(240, 40, 100, 30))
        self.splitter_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.splitter_btn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.splitter_btn.setFont(font)
        self.splitter_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.splitter_btn.setObjectName("splitter_btn")
        self.stage_ind = QtWidgets.QPushButton(self.groupBox_18)
        self.stage_ind.setGeometry(QtCore.QRect(350, 20, 55, 55))
        self.stage_ind.setMinimumSize(QtCore.QSize(55, 55))
        self.stage_ind.setMaximumSize(QtCore.QSize(55, 55))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stage_ind.setFont(font)
        self.stage_ind.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border: rgb(0, 255, 0);")
        self.stage_ind.setObjectName("stage_ind")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_21.setGeometry(QtCore.QRect(0, 0, 430, 205))
        self.groupBox_21.setMinimumSize(QtCore.QSize(430, 205))
        self.groupBox_21.setMaximumSize(QtCore.QSize(430, 205))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_21.setObjectName("groupBox_21")
        self.exp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.exp_lbl.setGeometry(QtCore.QRect(10, 30, 100, 20))
        self.exp_lbl.setMinimumSize(QtCore.QSize(100, 20))
        self.exp_lbl.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_lbl.setFont(font)
        self.exp_lbl.setObjectName("exp_lbl")
        self.exp_inp = QtWidgets.QLineEdit(self.groupBox_21)
        self.exp_inp.setGeometry(QtCore.QRect(110, 30, 45, 20))
        self.exp_inp.setMinimumSize(QtCore.QSize(45, 20))
        self.exp_inp.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_inp.setFont(font)
        self.exp_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exp_inp.setObjectName("exp_inp")
        self.num_exp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.num_exp_lbl.setGeometry(QtCore.QRect(170, 30, 45, 20))
        self.num_exp_lbl.setMinimumSize(QtCore.QSize(45, 20))
        self.num_exp_lbl.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num_exp_lbl.setFont(font)
        self.num_exp_lbl.setObjectName("num_exp_lbl")
        self.num_exp_spn = QtWidgets.QSpinBox(self.groupBox_21)
        self.num_exp_spn.setGeometry(QtCore.QRect(220, 30, 45, 20))
        self.num_exp_spn.setMinimumSize(QtCore.QSize(45, 20))
        self.num_exp_spn.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num_exp_spn.setFont(font)
        self.num_exp_spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_exp_spn.setObjectName("num_exp_spn")
        self.exp_btn2 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn2.setGeometry(QtCore.QRect(290, 110, 120, 60))
        self.exp_btn2.setMinimumSize(QtCore.QSize(120, 60))
        self.exp_btn2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.exp_btn2.setFont(font)
        self.exp_btn2.setStyleSheet("background-color: rgb(255, 92, 42);\n"
"")
        self.exp_btn2.setObjectName("exp_btn2")
        self.remaining_lbl2 = QtWidgets.QLabel(self.groupBox_21)
        self.remaining_lbl2.setGeometry(QtCore.QRect(170, 80, 40, 20))
        self.remaining_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.remaining_lbl2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remaining_lbl2.setFont(font)
        self.remaining_lbl2.setObjectName("remaining_lbl2")
        self.currentexp_lbl2 = QtWidgets.QLabel(self.groupBox_21)
        self.currentexp_lbl2.setGeometry(QtCore.QRect(50, 80, 40, 20))
        self.currentexp_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.currentexp_lbl2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.currentexp_lbl2.setFont(font)
        self.currentexp_lbl2.setObjectName("currentexp_lbl2")
        self.currentexp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.currentexp_lbl.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.currentexp_lbl.setMinimumSize(QtCore.QSize(95, 0))
        self.currentexp_lbl.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentexp_lbl.setFont(font)
        self.currentexp_lbl.setObjectName("currentexp_lbl")
        self.remaining_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.remaining_lbl.setGeometry(QtCore.QRect(130, 60, 120, 20))
        self.remaining_lbl.setMinimumSize(QtCore.QSize(120, 20))
        self.remaining_lbl.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.remaining_lbl.setFont(font)
        self.remaining_lbl.setObjectName("remaining_lbl")
        self.exp_prog_2 = QtWidgets.QProgressBar(self.groupBox_21)
        self.exp_prog_2.setGeometry(QtCore.QRect(10, 140, 265, 18))
        self.exp_prog_2.setMinimumSize(QtCore.QSize(265, 18))
        self.exp_prog_2.setMaximumSize(QtCore.QSize(265, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exp_prog_2.setFont(font)
        self.exp_prog_2.setStyleSheet("")
        self.exp_prog_2.setProperty("value", 100)
        self.exp_prog_2.setTextVisible(True)
        self.exp_prog_2.setOrientation(QtCore.Qt.Horizontal)
        self.exp_prog_2.setObjectName("exp_prog_2")
        self.exp_btn = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn.setGeometry(QtCore.QRect(290, 40, 120, 60))
        self.exp_btn.setMinimumSize(QtCore.QSize(120, 60))
        self.exp_btn.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_btn.setFont(font)
        self.exp_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"\n"
"")
        self.exp_btn.setObjectName("exp_btn")
        self.exp_prog = QtWidgets.QProgressBar(self.groupBox_21)
        self.exp_prog.setGeometry(QtCore.QRect(10, 110, 265, 18))
        self.exp_prog.setMinimumSize(QtCore.QSize(265, 18))
        self.exp_prog.setMaximumSize(QtCore.QSize(265, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exp_prog.setFont(font)
        self.exp_prog.setStyleSheet("")
        self.exp_prog.setProperty("value", 100)
        self.exp_prog.setTextVisible(True)
        self.exp_prog.setOrientation(QtCore.Qt.Horizontal)
        self.exp_prog.setObjectName("exp_prog")
        self.last_exposed = QtWidgets.QLabel(self.groupBox_21)
        self.last_exposed.setGeometry(QtCore.QRect(10, 170, 95, 20))
        self.last_exposed.setMinimumSize(QtCore.QSize(95, 20))
        self.last_exposed.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_exposed.setFont(font)
        self.last_exposed.setObjectName("last_exposed")
        self.last_exposed_2 = QtWidgets.QLabel(self.groupBox_21)
        self.last_exposed_2.setGeometry(QtCore.QRect(110, 170, 295, 20))
        self.last_exposed_2.setMinimumSize(QtCore.QSize(295, 20))
        self.last_exposed_2.setMaximumSize(QtCore.QSize(295, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_exposed_2.setFont(font)
        self.last_exposed_2.setObjectName("last_exposed_2")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_22.setGeometry(QtCore.QRect(0, 520, 235, 150))
        self.groupBox_22.setMinimumSize(QtCore.QSize(235, 150))
        self.groupBox_22.setMaximumSize(QtCore.QSize(235, 150))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.ds9_btn = QtWidgets.QPushButton(self.groupBox_22)
        self.ds9_btn.setGeometry(QtCore.QRect(180, 10, 50, 130))
        self.ds9_btn.setMinimumSize(QtCore.QSize(50, 130))
        self.ds9_btn.setMaximumSize(QtCore.QSize(50, 130))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ds9_btn.setFont(font)
        self.ds9_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.ds9_btn.setObjectName("ds9_btn")
        self.ds9_list = QtWidgets.QListWidget(self.groupBox_22)
        self.ds9_list.setGeometry(QtCore.QRect(10, 10, 160, 130))
        self.ds9_list.setMinimumSize(QtCore.QSize(160, 130))
        self.ds9_list.setMaximumSize(QtCore.QSize(160, 130))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ds9_list.setFont(font)
        self.ds9_list.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ds9_list.setObjectName("ds9_list")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 0, 420, 760))
        self.groupBox_19.setMinimumSize(QtCore.QSize(420, 760))
        self.groupBox_19.setMaximumSize(QtCore.QSize(420, 760))
        self.groupBox_19.setStyleSheet("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_24.setGeometry(QtCore.QRect(0, 200, 420, 215))
        self.groupBox_24.setMinimumSize(QtCore.QSize(420, 215))
        self.groupBox_24.setMaximumSize(QtCore.QSize(420, 215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_24.setObjectName("groupBox_24")
        self.temp_lbl = QtWidgets.QLabel(self.groupBox_24)
        self.temp_lbl.setGeometry(QtCore.QRect(10, 30, 97, 20))
        self.temp_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.temp_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.temp_lbl.setFont(font)
        self.temp_lbl.setObjectName("temp_lbl")
        self.temp_lineEdit = QtWidgets.QLineEdit(self.groupBox_24)
        self.temp_lineEdit.setGeometry(QtCore.QRect(100, 30, 70, 20))
        self.temp_lineEdit.setMinimumSize(QtCore.QSize(70, 20))
        self.temp_lineEdit.setMaximumSize(QtCore.QSize(70, 20))
        self.temp_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_lineEdit.setStyleSheet("background-color: rgb(255,255,255);")
        self.temp_lineEdit.setObjectName("temp_lineEdit")
        self.temp_setbtn = QtWidgets.QPushButton(self.groupBox_24)
        self.temp_setbtn.setGeometry(QtCore.QRect(180, 30, 30, 20))
        self.temp_setbtn.setMinimumSize(QtCore.QSize(30, 20))
        self.temp_setbtn.setMaximumSize(QtCore.QSize(30, 20))
        self.temp_setbtn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.temp_setbtn.setObjectName("temp_setbtn")
        self.ctemp_lbl = QtWidgets.QLabel(self.groupBox_24)
        self.ctemp_lbl.setGeometry(QtCore.QRect(220, 30, 101, 20))
        self.ctemp_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.ctemp_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.ctemp_lbl.setFont(font)
        self.ctemp_lbl.setObjectName("ctemp_lbl")
        self.ctemp_lbl2 = QtWidgets.QLabel(self.groupBox_24)
        self.ctemp_lbl2.setGeometry(QtCore.QRect(330, 30, 40, 20))
        self.ctemp_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.ctemp_lbl2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.ctemp_lbl2.setFont(font)
        self.ctemp_lbl2.setObjectName("ctemp_lbl2")
        self.cooler_lbl = QtWidgets.QLabel(self.groupBox_24)
        self.cooler_lbl.setGeometry(QtCore.QRect(10, 60, 50, 20))
        self.cooler_lbl.setMinimumSize(QtCore.QSize(50, 20))
        self.cooler_lbl.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.cooler_lbl.setFont(font)
        self.cooler_lbl.setObjectName("cooler_lbl")
        self.cooler_rdb_on = QtWidgets.QRadioButton(self.groupBox_24)
        self.cooler_rdb_on.setGeometry(QtCore.QRect(70, 60, 50, 20))
        self.cooler_rdb_on.setMinimumSize(QtCore.QSize(50, 20))
        self.cooler_rdb_on.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cooler_rdb_on.setFont(font)
        self.cooler_rdb_on.setIconSize(QtCore.QSize(20, 20))
        self.cooler_rdb_on.setObjectName("cooler_rdb_on")
        self.cooler_rdb_off = QtWidgets.QRadioButton(self.groupBox_24)
        self.cooler_rdb_off.setGeometry(QtCore.QRect(130, 60, 60, 20))
        self.cooler_rdb_off.setMinimumSize(QtCore.QSize(60, 20))
        self.cooler_rdb_off.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cooler_rdb_off.setFont(font)
        self.cooler_rdb_off.setObjectName("cooler_rdb_off")
        self.cpower_lbl = QtWidgets.QLabel(self.groupBox_24)
        self.cpower_lbl.setGeometry(QtCore.QRect(220, 60, 90, 20))
        self.cpower_lbl.setMinimumSize(QtCore.QSize(90, 20))
        self.cpower_lbl.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cpower_lbl.setFont(font)
        self.cpower_lbl.setObjectName("cpower_lbl")
        self.cpower_lbl2 = QtWidgets.QLabel(self.groupBox_24)
        self.cpower_lbl2.setGeometry(QtCore.QRect(330, 60, 40, 20))
        self.cpower_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.cpower_lbl2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cpower_lbl2.setFont(font)
        self.cpower_lbl2.setObjectName("cpower_lbl2")
        self.tempgraph = PlotWidget(self.groupBox_24)
        self.tempgraph.setGeometry(QtCore.QRect(10, 90, 400, 120))
        self.tempgraph.setMinimumSize(QtCore.QSize(400, 120))
        self.tempgraph.setMaximumSize(QtCore.QSize(400, 120))
        self.tempgraph.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tempgraph.setObjectName("tempgraph")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 150, 420, 45))
        self.groupBox_23.setMinimumSize(QtCore.QSize(420, 45))
        self.groupBox_23.setMaximumSize(QtCore.QSize(420, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.frameType_lbl = QtWidgets.QLabel(self.groupBox_23)
        self.frameType_lbl.setGeometry(QtCore.QRect(10, 10, 90, 20))
        self.frameType_lbl.setMinimumSize(QtCore.QSize(90, 20))
        self.frameType_lbl.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.frameType_lbl.setFont(font)
        self.frameType_lbl.setObjectName("frameType_lbl")
        self.frameType_rdb_light = QtWidgets.QRadioButton(self.groupBox_23)
        self.frameType_rdb_light.setGeometry(QtCore.QRect(110, 10, 60, 20))
        self.frameType_rdb_light.setMinimumSize(QtCore.QSize(60, 20))
        self.frameType_rdb_light.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameType_rdb_light.setFont(font)
        self.frameType_rdb_light.setIconSize(QtCore.QSize(20, 20))
        self.frameType_rdb_light.setObjectName("frameType_rdb_light")
        self.frameType_rdb_flat = QtWidgets.QRadioButton(self.groupBox_23)
        self.frameType_rdb_flat.setGeometry(QtCore.QRect(180, 10, 60, 20))
        self.frameType_rdb_flat.setMinimumSize(QtCore.QSize(60, 20))
        self.frameType_rdb_flat.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameType_rdb_flat.setFont(font)
        self.frameType_rdb_flat.setIconSize(QtCore.QSize(20, 20))
        self.frameType_rdb_flat.setObjectName("frameType_rdb_flat")
        self.frameType_rdb_dark = QtWidgets.QRadioButton(self.groupBox_23)
        self.frameType_rdb_dark.setGeometry(QtCore.QRect(240, 10, 60, 20))
        self.frameType_rdb_dark.setMinimumSize(QtCore.QSize(60, 20))
        self.frameType_rdb_dark.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameType_rdb_dark.setFont(font)
        self.frameType_rdb_dark.setIconSize(QtCore.QSize(20, 20))
        self.frameType_rdb_dark.setObjectName("frameType_rdb_dark")
        self.frameType_rdb_bias = QtWidgets.QRadioButton(self.groupBox_23)
        self.frameType_rdb_bias.setGeometry(QtCore.QRect(310, 10, 60, 20))
        self.frameType_rdb_bias.setMinimumSize(QtCore.QSize(60, 20))
        self.frameType_rdb_bias.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameType_rdb_bias.setFont(font)
        self.frameType_rdb_bias.setIconSize(QtCore.QSize(20, 20))
        self.frameType_rdb_bias.setObjectName("frameType_rdb_bias")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 10, 420, 150))
        self.groupBox_25.setMinimumSize(QtCore.QSize(420, 150))
        self.groupBox_25.setMaximumSize(QtCore.QSize(420, 150))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_25.setFont(font)
        self.groupBox_25.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_25.setObjectName("groupBox_25")
        self.bin_lbl = QtWidgets.QLabel(self.groupBox_25)
        self.bin_lbl.setGeometry(QtCore.QRect(10, 30, 60, 20))
        self.bin_lbl.setMinimumSize(QtCore.QSize(60, 20))
        self.bin_lbl.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.bin_lbl.setFont(font)
        self.bin_lbl.setObjectName("bin_lbl")
        self.etc_x = QtWidgets.QLabel(self.groupBox_25)
        self.etc_x.setGeometry(QtCore.QRect(70, 30, 10, 20))
        self.etc_x.setMinimumSize(QtCore.QSize(10, 20))
        self.etc_x.setMaximumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.etc_x.setFont(font)
        self.etc_x.setObjectName("etc_x")
        self.xbin_spinbtn = QtWidgets.QSpinBox(self.groupBox_25)
        self.xbin_spinbtn.setGeometry(QtCore.QRect(90, 30, 50, 20))
        self.xbin_spinbtn.setMinimumSize(QtCore.QSize(50, 20))
        self.xbin_spinbtn.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xbin_spinbtn.setFont(font)
        self.xbin_spinbtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xbin_spinbtn.setObjectName("xbin_spinbtn")
        self.etc_y = QtWidgets.QLabel(self.groupBox_25)
        self.etc_y.setGeometry(QtCore.QRect(150, 30, 10, 20))
        self.etc_y.setMinimumSize(QtCore.QSize(10, 20))
        self.etc_y.setMaximumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.etc_y.setFont(font)
        self.etc_y.setObjectName("etc_y")
        self.ybin_spinbtn = QtWidgets.QSpinBox(self.groupBox_25)
        self.ybin_spinbtn.setGeometry(QtCore.QRect(170, 30, 50, 20))
        self.ybin_spinbtn.setMinimumSize(QtCore.QSize(50, 20))
        self.ybin_spinbtn.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ybin_spinbtn.setFont(font)
        self.ybin_spinbtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ybin_spinbtn.setObjectName("ybin_spinbtn")
        self.gain_lbl = QtWidgets.QLabel(self.groupBox_25)
        self.gain_lbl.setGeometry(QtCore.QRect(10, 60, 40, 20))
        self.gain_lbl.setMinimumSize(QtCore.QSize(40, 20))
        self.gain_lbl.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.gain_lbl.setFont(font)
        self.gain_lbl.setObjectName("gain_lbl")
        self.offset_lbl = QtWidgets.QLabel(self.groupBox_25)
        self.offset_lbl.setGeometry(QtCore.QRect(10, 90, 50, 20))
        self.offset_lbl.setMinimumSize(QtCore.QSize(50, 20))
        self.offset_lbl.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.offset_lbl.setFont(font)
        self.offset_lbl.setObjectName("offset_lbl")
        self.band_lbl = QtWidgets.QLabel(self.groupBox_25)
        self.band_lbl.setGeometry(QtCore.QRect(10, 120, 75, 20))
        self.band_lbl.setMinimumSize(QtCore.QSize(75, 20))
        self.band_lbl.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.band_lbl.setFont(font)
        self.band_lbl.setObjectName("band_lbl")
        self.gain_spn = QtWidgets.QSpinBox(self.groupBox_25)
        self.gain_spn.setGeometry(QtCore.QRect(90, 60, 50, 20))
        self.gain_spn.setMinimumSize(QtCore.QSize(50, 20))
        self.gain_spn.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gain_spn.setFont(font)
        self.gain_spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gain_spn.setObjectName("gain_spn")
        self.offset_spn = QtWidgets.QSpinBox(self.groupBox_25)
        self.offset_spn.setGeometry(QtCore.QRect(90, 90, 50, 20))
        self.offset_spn.setMinimumSize(QtCore.QSize(50, 20))
        self.offset_spn.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.offset_spn.setFont(font)
        self.offset_spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.offset_spn.setObjectName("offset_spn")
        self.band_spn = QtWidgets.QSpinBox(self.groupBox_25)
        self.band_spn.setGeometry(QtCore.QRect(90, 120, 50, 20))
        self.band_spn.setMinimumSize(QtCore.QSize(50, 20))
        self.band_spn.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.band_spn.setFont(font)
        self.band_spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.band_spn.setObjectName("band_spn")
        self.eight_rdb = QtWidgets.QRadioButton(self.groupBox_25)
        self.eight_rdb.setGeometry(QtCore.QRect(160, 70, 60, 20))
        self.eight_rdb.setMinimumSize(QtCore.QSize(60, 20))
        self.eight_rdb.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.eight_rdb.setFont(font)
        self.eight_rdb.setObjectName("eight_rdb")
        self.sixteen_rdb = QtWidgets.QRadioButton(self.groupBox_25)
        self.sixteen_rdb.setGeometry(QtCore.QRect(160, 100, 60, 20))
        self.sixteen_rdb.setMinimumSize(QtCore.QSize(60, 20))
        self.sixteen_rdb.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sixteen_rdb.setFont(font)
        self.sixteen_rdb.setObjectName("sixteen_rdb")
        self.frameSize_lbl = QtWidgets.QLabel(self.groupBox_25)
        self.frameSize_lbl.setGeometry(QtCore.QRect(280, 30, 120, 20))
        self.frameSize_lbl.setMinimumSize(QtCore.QSize(120, 20))
        self.frameSize_lbl.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameSize_lbl.setFont(font)
        self.frameSize_lbl.setObjectName("frameSize_lbl")
        self.etc_x2 = QtWidgets.QLabel(self.groupBox_25)
        self.etc_x2.setGeometry(QtCore.QRect(240, 60, 20, 20))
        self.etc_x2.setMinimumSize(QtCore.QSize(20, 20))
        self.etc_x2.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.etc_x2.setFont(font)
        self.etc_x2.setObjectName("etc_x2")
        self.xframe_size = QtWidgets.QLineEdit(self.groupBox_25)
        self.xframe_size.setGeometry(QtCore.QRect(260, 60, 55, 20))
        self.xframe_size.setMinimumSize(QtCore.QSize(55, 20))
        self.xframe_size.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xframe_size.setFont(font)
        self.xframe_size.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xframe_size.setObjectName("xframe_size")
        self.etc_y2 = QtWidgets.QLabel(self.groupBox_25)
        self.etc_y2.setGeometry(QtCore.QRect(330, 60, 20, 20))
        self.etc_y2.setMinimumSize(QtCore.QSize(20, 20))
        self.etc_y2.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.etc_y2.setFont(font)
        self.etc_y2.setObjectName("etc_y2")
        self.yframe_size = QtWidgets.QLineEdit(self.groupBox_25)
        self.yframe_size.setGeometry(QtCore.QRect(350, 60, 55, 20))
        self.yframe_size.setMinimumSize(QtCore.QSize(55, 20))
        self.yframe_size.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yframe_size.setFont(font)
        self.yframe_size.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yframe_size.setObjectName("yframe_size")
        self.topmost = QtWidgets.QLabel(self.groupBox_25)
        self.topmost.setGeometry(QtCore.QRect(270, 90, 75, 20))
        self.topmost.setMinimumSize(QtCore.QSize(75, 20))
        self.topmost.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.topmost.setFont(font)
        self.topmost.setObjectName("topmost")
        self.tpmost_lineEdit = QtWidgets.QLineEdit(self.groupBox_25)
        self.tpmost_lineEdit.setGeometry(QtCore.QRect(350, 90, 55, 20))
        self.tpmost_lineEdit.setMinimumSize(QtCore.QSize(55, 20))
        self.tpmost_lineEdit.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tpmost_lineEdit.setFont(font)
        self.tpmost_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tpmost_lineEdit.setText("")
        self.tpmost_lineEdit.setObjectName("tpmost_lineEdit")
        self.leftmost = QtWidgets.QLabel(self.groupBox_25)
        self.leftmost.setGeometry(QtCore.QRect(270, 120, 75, 20))
        self.leftmost.setMinimumSize(QtCore.QSize(75, 20))
        self.leftmost.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leftmost.setFont(font)
        self.leftmost.setObjectName("leftmost")
        self.leftmost_lineEdit = QtWidgets.QLineEdit(self.groupBox_25)
        self.leftmost_lineEdit.setGeometry(QtCore.QRect(350, 120, 55, 20))
        self.leftmost_lineEdit.setMinimumSize(QtCore.QSize(55, 20))
        self.leftmost_lineEdit.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leftmost_lineEdit.setFont(font)
        self.leftmost_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.leftmost_lineEdit.setText("")
        self.leftmost_lineEdit.setObjectName("leftmost_lineEdit")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_26.setGeometry(QtCore.QRect(0, 420, 420, 255))
        self.groupBox_26.setMinimumSize(QtCore.QSize(420, 255))
        self.groupBox_26.setMaximumSize(QtCore.QSize(420, 255))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_26.setTitle("")
        self.groupBox_26.setObjectName("groupBox_26")
        self.fluxgraph = PlotWidget(self.groupBox_26)
        self.fluxgraph.setGeometry(QtCore.QRect(10, 20, 400, 211))
        self.fluxgraph.setMinimumSize(QtCore.QSize(400, 100))
        self.fluxgraph.setMaximumSize(QtCore.QSize(400, 250))
        self.fluxgraph.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fluxgraph.setObjectName("fluxgraph")
        self.tabWidget.addTab(self.tab_6, "")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_15.setGeometry(QtCore.QRect(440, 10, 636, 400))
        self.groupBox_15.setMinimumSize(QtCore.QSize(636, 400))
        self.groupBox_15.setMaximumSize(QtCore.QSize(636, 400))
        self.groupBox_15.setObjectName("groupBox_15")
        self.ds9_here = QtWidgets.QLabel(self.groupBox_15)
        self.ds9_here.setGeometry(QtCore.QRect(0, 0, 636, 400))
        self.ds9_here.setMinimumSize(QtCore.QSize(636, 400))
        self.ds9_here.setMaximumSize(QtCore.QSize(636, 400))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ds9_here.setFont(font)
        self.ds9_here.setStyleSheet("color: rgb(255, 255, 255);")
        self.ds9_here.setText("")
        self.ds9_here.setObjectName("ds9_here")
        self.newds9_btn = QtWidgets.QPushButton(self.groupBox_15)
        self.newds9_btn.setGeometry(QtCore.QRect(260, 180, 130, 40))
        self.newds9_btn.setMinimumSize(QtCore.QSize(130, 40))
        self.newds9_btn.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.newds9_btn.setFont(font)
        self.newds9_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.newds9_btn.setObjectName("newds9_btn")
        self.gridLayout.addWidget(self.groupBox_8, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FHiRE GUI"))
        self.groupBox_8.setTitle(_translate("MainWindow", "GroupBox"))
        self.claudius_lbl1.setText(_translate("MainWindow", ">>>"))
        self.claudius_lbl2.setText(_translate("MainWindow", "Send terminal commands directly to Claudius. (ex: nn2) \n"
" Terminal output displayed above."))
        self.groupBox_17.setTitle(_translate("MainWindow", "Centroid     -------------------------------------------"))
        self.centroid_lbl.setText(_translate("MainWindow", "(0,0)"))
        self.printcen_btn.setText(_translate("MainWindow", "Print Centroid"))
        self.move_lbl.setText(_translate("MainWindow", "Move:"))
        self.move_lbl_2.setText(_translate("MainWindow", "------"))
        self.move_btn.setText(_translate("MainWindow", "Move"))
        self.auto_on_rdb.setText(_translate("MainWindow", "ON"))
        self.auto_off_rdb.setText(_translate("MainWindow", "OFF"))
        self.saving_on_rdb.setText(_translate("MainWindow", "ON"))
        self.saving_off_rdb.setText(_translate("MainWindow", "OFF"))
        self.auto_lbl.setText(_translate("MainWindow", "Auto Guiding:"))
        self.saving_lbl.setText(_translate("MainWindow", "Save Guider\n"
"Images:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Focus     -------------------------------"))
        self.camera_2.setTitle(_translate("MainWindow", "Camera"))
        self.cfocus_btn_sub.setText(_translate("MainWindow", "-"))
        self.cfocus_btn_add.setText(_translate("MainWindow", "+"))
        self.cfocus_lbl.setText(_translate("MainWindow", "Count:"))
        self.cfocus_count.setText(_translate("MainWindow", "0"))
        self.cfocus_setbtn.setText(_translate("MainWindow", "Set"))
        self.ADC_2.setTitle(_translate("MainWindow", "ADC"))
        self.afocus1_btn_sub.setText(_translate("MainWindow", "-"))
        self.afocus1_btn_add.setText(_translate("MainWindow", "+"))
        self.afocus2_btn_sub.setText(_translate("MainWindow", "-"))
        self.afocus2_btn_add.setText(_translate("MainWindow", "+"))
        self.afocus1_count.setText(_translate("MainWindow", "0"))
        self.afocus1_lbl.setText(_translate("MainWindow", "Count:"))
        self.afocus2_lbl.setText(_translate("MainWindow", "Count:"))
        self.afcous2_count.setText(_translate("MainWindow", "0"))
        self.afocus1_setbtn.setText(_translate("MainWindow", "Set"))
        self.afocus2_setbtn.setText(_translate("MainWindow", "Set"))
        self.destination_path_2.setTitle(_translate("MainWindow", "Destination Path (ex: /home/fhire)"))
        self.dir_tool_btn_2.setText(_translate("MainWindow", "..."))
        self.dir_inp.setPlaceholderText(_translate("MainWindow", "/home/fhire"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Image Prefix (ex: GAMimage)"))
        self.prefix_inp.setPlaceholderText(_translate("MainWindow", "XXX_01.fit"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Filter     -------------------------------------------------------------------------------"))
        self.filter_btn.setText(_translate("MainWindow", "Set"))
        self.filter_ind.setText(_translate("MainWindow", "OKAY"))
        self.filter_cmb.setItemText(0, _translate("MainWindow", "ND 1.8"))
        self.filter_cmb.setItemText(1, _translate("MainWindow", "ND 3.0"))
        self.filter_cmb.setItemText(2, _translate("MainWindow", "V Filter"))
        self.filter_cmb.setItemText(3, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(4, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(5, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(6, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(7, _translate("MainWindow", "Empty"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Stage     ------------------------------------------------------------------------------"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.mirror_btn.setText(_translate("MainWindow", "Mirror"))
        self.splitter_btn.setText(_translate("MainWindow", "Splitter"))
        self.stage_ind.setText(_translate("MainWindow", "OKAY"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Exposure     ------------------------------------------------------------------------"))
        self.exp_lbl.setText(_translate("MainWindow", "Exp Time (s):"))
        self.num_exp_lbl.setText(_translate("MainWindow", "# Exp:"))
        self.exp_btn2.setText(_translate("MainWindow", "Abort"))
        self.remaining_lbl2.setText(_translate("MainWindow", "56s"))
        self.currentexp_lbl2.setText(_translate("MainWindow", "1"))
        self.currentexp_lbl.setText(_translate("MainWindow", "Current Exp:"))
        self.remaining_lbl.setText(_translate("MainWindow", "Remaining Time:"))
        self.exp_prog_2.setFormat(_translate("MainWindow", "%ps"))
        self.exp_btn.setText(_translate("MainWindow", "Expose"))
        self.exp_prog.setFormat(_translate("MainWindow", "%ps"))
        self.last_exposed.setText(_translate("MainWindow", "Last Exposed:"))
        self.last_exposed_2.setText(_translate("MainWindow", "---------------------"))
        self.ds9_btn.setText(_translate("MainWindow", "Open \n"
" ds9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Main"))
        self.groupBox_19.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Temperature     --------------------------------------------------------------------"))
        self.temp_lbl.setText(_translate("MainWindow", "CCD Temp:"))
        self.temp_setbtn.setText(_translate("MainWindow", "Set"))
        self.ctemp_lbl.setText(_translate("MainWindow", "Current Temp:"))
        self.ctemp_lbl2.setText(_translate("MainWindow", "---- C"))
        self.cooler_lbl.setText(_translate("MainWindow", "Cooler:"))
        self.cooler_rdb_on.setText(_translate("MainWindow", "ON"))
        self.cooler_rdb_off.setText(_translate("MainWindow", "OFF"))
        self.cpower_lbl.setText(_translate("MainWindow", "Cooler Power:"))
        self.cpower_lbl2.setText(_translate("MainWindow", "0 %"))
        self.frameType_lbl.setText(_translate("MainWindow", "Frame Type:"))
        self.frameType_rdb_light.setText(_translate("MainWindow", "Light"))
        self.frameType_rdb_flat.setText(_translate("MainWindow", "Flat"))
        self.frameType_rdb_dark.setText(_translate("MainWindow", "Dark"))
        self.frameType_rdb_bias.setText(_translate("MainWindow", "Bias"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Frame     -----------------------------------------------------------------------------"))
        self.bin_lbl.setText(_translate("MainWindow", "Binning:"))
        self.etc_x.setText(_translate("MainWindow", "X"))
        self.etc_y.setText(_translate("MainWindow", "Y"))
        self.gain_lbl.setText(_translate("MainWindow", "Gain:"))
        self.offset_lbl.setText(_translate("MainWindow", "Offset:"))
        self.band_lbl.setText(_translate("MainWindow", "Bandwidth:"))
        self.eight_rdb.setText(_translate("MainWindow", "8 Bit"))
        self.sixteen_rdb.setText(_translate("MainWindow", "16 Bit"))
        self.frameSize_lbl.setText(_translate("MainWindow", "Frame Size (px):"))
        self.etc_x2.setText(_translate("MainWindow", "X"))
        self.etc_y2.setText(_translate("MainWindow", "Y"))
        self.topmost.setText(_translate("MainWindow", "Top-most:"))
        self.leftmost.setText(_translate("MainWindow", "Left-most:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Settings"))
        self.groupBox_15.setTitle(_translate("MainWindow", "GroupBox"))
        self.newds9_btn.setText(_translate("MainWindow", "Open New DS9\n"
"Window"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

