# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fhireGUI11.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 514)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1122, 747))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(40,40,40)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(426, 10, 270, 475))
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 260))
        self.groupBox_2.setMaximumSize(QtCore.QSize(630, 733))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.terminal_edit = QtWidgets.QTextEdit(self.groupBox_2)
        self.terminal_edit.setGeometry(QtCore.QRect(10, 120, 231, 272))
        self.terminal_edit.setMinimumSize(QtCore.QSize(200, 150))
        self.terminal_edit.setMaximumSize(QtCore.QSize(800, 700))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.terminal_edit.setFont(font)
        self.terminal_edit.setStyleSheet("background-color: rgb(255,255,255);")
        self.terminal_edit.setObjectName("terminal_edit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 400, 250, 65))
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 50))
        self.groupBox_6.setMaximumSize(QtCore.QSize(640, 200))
        self.groupBox_6.setStyleSheet("::title {color: rgb(255,255,255)}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.claudius_lbl1 = QtWidgets.QLabel(self.groupBox_6)
        self.claudius_lbl1.setGeometry(QtCore.QRect(0, 30, 23, 25))
        self.claudius_lbl1.setMinimumSize(QtCore.QSize(0, 25))
        self.claudius_lbl1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.claudius_lbl1.setFont(font)
        self.claudius_lbl1.setStyleSheet("color: rgb(255,255,255)")
        self.claudius_lbl1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.claudius_lbl1.setObjectName("claudius_lbl1")
        self.claudius_command_lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.claudius_command_lineEdit.setGeometry(QtCore.QRect(30, 30, 210, 25))
        self.claudius_command_lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.claudius_command_lineEdit.setMaximumSize(QtCore.QSize(350, 25))
        self.claudius_command_lineEdit.setStyleSheet("background-color: rgb(255,255,255)")
        self.claudius_command_lineEdit.setText("")
        self.claudius_command_lineEdit.setObjectName("claudius_command_lineEdit")
        self.claudius_lbl2 = QtWidgets.QLabel(self.groupBox_6)
        self.claudius_lbl2.setGeometry(QtCore.QRect(0, -10, 246, 40))
        self.claudius_lbl2.setMinimumSize(QtCore.QSize(200, 40))
        self.claudius_lbl2.setMaximumSize(QtCore.QSize(320, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.claudius_lbl2.setFont(font)
        self.claudius_lbl2.setStyleSheet("color: rgb(0, 255, 0)")
        self.claudius_lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.claudius_lbl2.setObjectName("claudius_lbl2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 0, 246, 115))
        self.groupBox_12.setMinimumSize(QtCore.QSize(100, 50))
        self.groupBox_12.setMaximumSize(QtCore.QSize(300, 275))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.testing_lbl = QtWidgets.QLabel(self.groupBox_12)
        self.testing_lbl.setGeometry(QtCore.QRect(170, 18, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.testing_lbl.setFont(font)
        self.testing_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.testing_lbl.setObjectName("testing_lbl")
        self.ADC_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.ADC_btn.setGeometry(QtCore.QRect(170, 38, 72, 18))
        self.ADC_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.ADC_btn.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ADC_btn.setFont(font)
        self.ADC_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.ADC_btn.setObjectName("ADC_btn")
        self.TCS_btn_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.TCS_btn_2.setGeometry(QtCore.QRect(170, 63, 72, 18))
        self.TCS_btn_2.setMinimumSize(QtCore.QSize(60, 10))
        self.TCS_btn_2.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TCS_btn_2.setFont(font)
        self.TCS_btn_2.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.TCS_btn_2.setObjectName("TCS_btn_2")
        self.settings_lbl = QtWidgets.QLabel(self.groupBox_12)
        self.settings_lbl.setGeometry(QtCore.QRect(90, 18, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.settings_lbl.setFont(font)
        self.settings_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_lbl.setObjectName("settings_lbl")
        self.guidingCam_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.guidingCam_btn.setGeometry(QtCore.QRect(90, 38, 72, 18))
        self.guidingCam_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.guidingCam_btn.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.guidingCam_btn.setFont(font)
        self.guidingCam_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.guidingCam_btn.setObjectName("guidingCam_btn")
        self.monitoring_lbl = QtWidgets.QLabel(self.groupBox_12)
        self.monitoring_lbl.setGeometry(QtCore.QRect(10, 18, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.monitoring_lbl.setFont(font)
        self.monitoring_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.monitoring_lbl.setObjectName("monitoring_lbl")
        self.TCS_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.TCS_btn.setGeometry(QtCore.QRect(10, 63, 72, 18))
        self.TCS_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.TCS_btn.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TCS_btn.setFont(font)
        self.TCS_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.TCS_btn.setObjectName("TCS_btn")
        self.brightness_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.brightness_btn.setGeometry(QtCore.QRect(10, 38, 72, 18))
        self.brightness_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.brightness_btn.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.brightness_btn.setFont(font)
        self.brightness_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.brightness_btn.setObjectName("brightness_btn")
        self.vacuum_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.vacuum_btn.setGeometry(QtCore.QRect(10, 88, 72, 18))
        self.vacuum_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.vacuum_btn.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vacuum_btn.setFont(font)
        self.vacuum_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.vacuum_btn.setObjectName("vacuum_btn")
        self.guiding_btn = QtWidgets.QPushButton(self.groupBox_12)
        self.guiding_btn.setGeometry(QtCore.QRect(170, 88, 72, 18))
        self.guiding_btn.setMinimumSize(QtCore.QSize(60, 10))
        self.guiding_btn.setMaximumSize(QtCore.QSize(79, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.guiding_btn.setFont(font)
        self.guiding_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.guiding_btn.setObjectName("guiding_btn")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(240, 120, 15, 272))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(2, 10, 432, 475))
        self.groupBox_4.setMinimumSize(QtCore.QSize(420, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(500, 750))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(280, 290, 150, 105))
        self.groupBox_9.setMinimumSize(QtCore.QSize(100, 50))
        self.groupBox_9.setMaximumSize(QtCore.QSize(190, 275))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.cfocus_count = QtWidgets.QLabel(self.groupBox_9)
        self.cfocus_count.setGeometry(QtCore.QRect(104, 78, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_count.setFont(font)
        self.cfocus_count.setStyleSheet("")
        self.cfocus_count.setObjectName("cfocus_count")
        self.cfocus_lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.cfocus_lineEdit.setGeometry(QtCore.QRect(57, 48, 40, 20))
        self.cfocus_lineEdit.setMinimumSize(QtCore.QSize(40, 20))
        self.cfocus_lineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.cfocus_lineEdit.setStyleSheet("background-color: rgb(255,255,255);")
        self.cfocus_lineEdit.setObjectName("cfocus_lineEdit")
        self.cfocus_btn_sub = QtWidgets.QPushButton(self.groupBox_9)
        self.cfocus_btn_sub.setGeometry(QtCore.QRect(31, 48, 20, 20))
        self.cfocus_btn_sub.setMinimumSize(QtCore.QSize(20, 20))
        self.cfocus_btn_sub.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_btn_sub.setFont(font)
        self.cfocus_btn_sub.setObjectName("cfocus_btn_sub")
        self.cfocus_lbl = QtWidgets.QLabel(self.groupBox_9)
        self.cfocus_lbl.setGeometry(QtCore.QRect(44, 78, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cfocus_lbl.setFont(font)
        self.cfocus_lbl.setStyleSheet("")
        self.cfocus_lbl.setObjectName("cfocus_lbl")
        self.cfocus_btn_add = QtWidgets.QPushButton(self.groupBox_9)
        self.cfocus_btn_add.setGeometry(QtCore.QRect(103, 48, 20, 20))
        self.cfocus_btn_add.setMinimumSize(QtCore.QSize(20, 20))
        self.cfocus_btn_add.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cfocus_btn_add.setFont(font)
        self.cfocus_btn_add.setObjectName("cfocus_btn_add")
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(10, 18, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.destination_path_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.destination_path_2.setGeometry(QtCore.QRect(0, 200, 275, 85))
        self.destination_path_2.setMinimumSize(QtCore.QSize(235, 65))
        self.destination_path_2.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.destination_path_2.setFont(font)
        self.destination_path_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.destination_path_2.setTitle("")
        self.destination_path_2.setObjectName("destination_path_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.destination_path_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.dir_inp = QtWidgets.QLineEdit(self.destination_path_2)
        self.dir_inp.setMinimumSize(QtCore.QSize(0, 20))
        self.dir_inp.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dir_inp.setFont(font)
        self.dir_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dir_inp.setObjectName("dir_inp")
        self.gridLayout_29.addWidget(self.dir_inp, 1, 1, 1, 1)
        self.dir_tool_btn_2 = QtWidgets.QToolButton(self.destination_path_2)
        self.dir_tool_btn_2.setMinimumSize(QtCore.QSize(0, 20))
        self.dir_tool_btn_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.dir_tool_btn_2.setObjectName("dir_tool_btn_2")
        self.gridLayout_29.addWidget(self.dir_tool_btn_2, 1, 2, 1, 1)
        self.prefix_inp = QtWidgets.QLineEdit(self.destination_path_2)
        self.prefix_inp.setMinimumSize(QtCore.QSize(125, 20))
        self.prefix_inp.setMaximumSize(QtCore.QSize(125, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prefix_inp.setFont(font)
        self.prefix_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.prefix_inp.setObjectName("prefix_inp")
        self.gridLayout_29.addWidget(self.prefix_inp, 0, 1, 1, 1)
        self.prefix_lbl = QtWidgets.QLabel(self.destination_path_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prefix_lbl.setFont(font)
        self.prefix_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prefix_lbl.setObjectName("prefix_lbl")
        self.gridLayout_29.addWidget(self.prefix_lbl, 0, 0, 1, 1)
        self.destin_lbl = QtWidgets.QLabel(self.destination_path_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.destin_lbl.setFont(font)
        self.destin_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.destin_lbl.setObjectName("destin_lbl")
        self.gridLayout_29.addWidget(self.destin_lbl, 1, 0, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 290, 275, 75))
        self.groupBox_11.setMinimumSize(QtCore.QSize(200, 20))
        self.groupBox_11.setMaximumSize(QtCore.QSize(300, 75))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.filter_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.filter_btn.setGeometry(QtCore.QRect(200, 30, 35, 20))
        self.filter_btn.setMinimumSize(QtCore.QSize(35, 20))
        self.filter_btn.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filter_btn.setFont(font)
        self.filter_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.filter_btn.setObjectName("filter_btn")
        self.filter_ind = QtWidgets.QLabel(self.groupBox_11)
        self.filter_ind.setGeometry(QtCore.QRect(20, 30, 15, 20))
        self.filter_ind.setMinimumSize(QtCore.QSize(10, 10))
        self.filter_ind.setMaximumSize(QtCore.QSize(125, 50))
        self.filter_ind.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.filter_ind.setText("")
        self.filter_ind.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_ind.setObjectName("filter_ind")
        self.filter_cmb = QtWidgets.QComboBox(self.groupBox_11)
        self.filter_cmb.setGeometry(QtCore.QRect(80, 30, 115, 20))
        self.filter_cmb.setMinimumSize(QtCore.QSize(115, 20))
        self.filter_cmb.setMaximumSize(QtCore.QSize(115, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filter_cmb.setFont(font)
        self.filter_cmb.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(191, 191, 191);")
        self.filter_cmb.setObjectName("filter_cmb")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_cmb.addItem("")
        self.filter_lbl = QtWidgets.QLabel(self.groupBox_11)
        self.filter_lbl.setGeometry(QtCore.QRect(40, 30, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filter_lbl.setFont(font)
        self.filter_lbl.setObjectName("filter_lbl")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_18.setGeometry(QtCore.QRect(280, 200, 150, 85))
        self.groupBox_18.setMinimumSize(QtCore.QSize(50, 80))
        self.groupBox_18.setMaximumSize(QtCore.QSize(430, 85))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.stage_ind = QtWidgets.QPushButton(self.groupBox_18)
        self.stage_ind.setGeometry(QtCore.QRect(10, 20, 15, 20))
        self.stage_ind.setMinimumSize(QtCore.QSize(15, 20))
        self.stage_ind.setMaximumSize(QtCore.QSize(55, 55))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stage_ind.setFont(font)
        self.stage_ind.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border: rgb(0, 255, 0);")
        self.stage_ind.setText("")
        self.stage_ind.setObjectName("stage_ind")
        self.home_rb = QtWidgets.QRadioButton(self.groupBox_18)
        self.home_rb.setGeometry(QtCore.QRect(70, 20, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.home_rb.setFont(font)
        self.home_rb.setObjectName("home_rb")
        self.mirror_rb = QtWidgets.QRadioButton(self.groupBox_18)
        self.mirror_rb.setGeometry(QtCore.QRect(70, 40, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mirror_rb.setFont(font)
        self.mirror_rb.setObjectName("mirror_rb")
        self.splitter_rb = QtWidgets.QRadioButton(self.groupBox_18)
        self.splitter_rb.setGeometry(QtCore.QRect(70, 60, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.splitter_rb.setFont(font)
        self.splitter_rb.setObjectName("splitter_rb")
        self.stage_lbl = QtWidgets.QLabel(self.groupBox_18)
        self.stage_lbl.setGeometry(QtCore.QRect(30, 20, 38, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stage_lbl.setFont(font)
        self.stage_lbl.setObjectName("stage_lbl")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_21.setGeometry(QtCore.QRect(0, 0, 430, 195))
        self.groupBox_21.setMinimumSize(QtCore.QSize(410, 160))
        self.groupBox_21.setMaximumSize(QtCore.QSize(430, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.exp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.exp_lbl.setGeometry(QtCore.QRect(30, 37, 100, 20))
        self.exp_lbl.setMinimumSize(QtCore.QSize(100, 20))
        self.exp_lbl.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_lbl.setFont(font)
        self.exp_lbl.setObjectName("exp_lbl")
        self.exp_inp = QtWidgets.QLineEdit(self.groupBox_21)
        self.exp_inp.setGeometry(QtCore.QRect(130, 37, 45, 20))
        self.exp_inp.setMinimumSize(QtCore.QSize(45, 20))
        self.exp_inp.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_inp.setFont(font)
        self.exp_inp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exp_inp.setObjectName("exp_inp")
        self.num_exp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.num_exp_lbl.setGeometry(QtCore.QRect(300, 37, 45, 20))
        self.num_exp_lbl.setMinimumSize(QtCore.QSize(45, 20))
        self.num_exp_lbl.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num_exp_lbl.setFont(font)
        self.num_exp_lbl.setObjectName("num_exp_lbl")
        self.num_exp_spn = QtWidgets.QSpinBox(self.groupBox_21)
        self.num_exp_spn.setGeometry(QtCore.QRect(340, 37, 45, 20))
        self.num_exp_spn.setMinimumSize(QtCore.QSize(45, 20))
        self.num_exp_spn.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num_exp_spn.setFont(font)
        self.num_exp_spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_exp_spn.setObjectName("num_exp_spn")
        self.exp_btn2 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn2.setGeometry(QtCore.QRect(230, 37, 42, 20))
        self.exp_btn2.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.exp_btn2.setFont(font)
        self.exp_btn2.setStyleSheet("background-color: rgb(255, 92, 42);\n"
"")
        self.exp_btn2.setObjectName("exp_btn2")
        self.remaining_lbl2 = QtWidgets.QLabel(self.groupBox_21)
        self.remaining_lbl2.setGeometry(QtCore.QRect(335, 97, 75, 20))
        self.remaining_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.remaining_lbl2.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remaining_lbl2.setFont(font)
        self.remaining_lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.remaining_lbl2.setObjectName("remaining_lbl2")
        self.currentexp_lbl2 = QtWidgets.QLabel(self.groupBox_21)
        self.currentexp_lbl2.setGeometry(QtCore.QRect(285, 97, 50, 20))
        self.currentexp_lbl2.setMinimumSize(QtCore.QSize(40, 20))
        self.currentexp_lbl2.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.currentexp_lbl2.setFont(font)
        self.currentexp_lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentexp_lbl2.setObjectName("currentexp_lbl2")
        self.currentexp_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.currentexp_lbl.setGeometry(QtCore.QRect(285, 74, 50, 25))
        self.currentexp_lbl.setMinimumSize(QtCore.QSize(20, 0))
        self.currentexp_lbl.setMaximumSize(QtCore.QSize(95, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentexp_lbl.setFont(font)
        self.currentexp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentexp_lbl.setObjectName("currentexp_lbl")
        self.remaining_lbl = QtWidgets.QLabel(self.groupBox_21)
        self.remaining_lbl.setGeometry(QtCore.QRect(335, 74, 75, 25))
        self.remaining_lbl.setMinimumSize(QtCore.QSize(20, 20))
        self.remaining_lbl.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.remaining_lbl.setFont(font)
        self.remaining_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.remaining_lbl.setObjectName("remaining_lbl")
        self.exp_prog_2 = QtWidgets.QProgressBar(self.groupBox_21)
        self.exp_prog_2.setGeometry(QtCore.QRect(10, 148, 400, 15))
        self.exp_prog_2.setMinimumSize(QtCore.QSize(265, 15))
        self.exp_prog_2.setMaximumSize(QtCore.QSize(400, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exp_prog_2.setFont(font)
        self.exp_prog_2.setStyleSheet("")
        self.exp_prog_2.setProperty("value", 100)
        self.exp_prog_2.setTextVisible(True)
        self.exp_prog_2.setOrientation(QtCore.Qt.Horizontal)
        self.exp_prog_2.setObjectName("exp_prog_2")
        self.exp_btn = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn.setGeometry(QtCore.QRect(180, 37, 45, 20))
        self.exp_btn.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_btn.setFont(font)
        self.exp_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"\n"
"")
        self.exp_btn.setObjectName("exp_btn")
        self.exp_prog = QtWidgets.QProgressBar(self.groupBox_21)
        self.exp_prog.setGeometry(QtCore.QRect(10, 128, 400, 15))
        self.exp_prog.setMinimumSize(QtCore.QSize(265, 15))
        self.exp_prog.setMaximumSize(QtCore.QSize(400, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exp_prog.setFont(font)
        self.exp_prog.setStyleSheet("")
        self.exp_prog.setProperty("value", 100)
        self.exp_prog.setTextVisible(True)
        self.exp_prog.setOrientation(QtCore.Qt.Horizontal)
        self.exp_prog.setObjectName("exp_prog")
        self.last_exposed = QtWidgets.QLabel(self.groupBox_21)
        self.last_exposed.setGeometry(QtCore.QRect(20, 168, 95, 20))
        self.last_exposed.setMinimumSize(QtCore.QSize(95, 20))
        self.last_exposed.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_exposed.setFont(font)
        self.last_exposed.setObjectName("last_exposed")
        self.last_exposed_2 = QtWidgets.QLabel(self.groupBox_21)
        self.last_exposed_2.setGeometry(QtCore.QRect(110, 168, 295, 20))
        self.last_exposed_2.setMinimumSize(QtCore.QSize(295, 20))
        self.last_exposed_2.setMaximumSize(QtCore.QSize(295, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_exposed_2.setFont(font)
        self.last_exposed_2.setObjectName("last_exposed_2")
        self.exp_inp_2 = QtWidgets.QLineEdit(self.groupBox_21)
        self.exp_inp_2.setGeometry(QtCore.QRect(130, 67, 45, 20))
        self.exp_inp_2.setMinimumSize(QtCore.QSize(45, 20))
        self.exp_inp_2.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_inp_2.setFont(font)
        self.exp_inp_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exp_inp_2.setObjectName("exp_inp_2")
        self.exp_inp_3 = QtWidgets.QLineEdit(self.groupBox_21)
        self.exp_inp_3.setGeometry(QtCore.QRect(130, 97, 45, 20))
        self.exp_inp_3.setMinimumSize(QtCore.QSize(45, 20))
        self.exp_inp_3.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_inp_3.setFont(font)
        self.exp_inp_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exp_inp_3.setObjectName("exp_inp_3")
        self.exp_btn2_2 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn2_2.setGeometry(QtCore.QRect(230, 67, 42, 20))
        self.exp_btn2_2.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn2_2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.exp_btn2_2.setFont(font)
        self.exp_btn2_2.setStyleSheet("background-color: rgb(255, 92, 42);\n"
"")
        self.exp_btn2_2.setObjectName("exp_btn2_2")
        self.exp_btn_2 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn_2.setGeometry(QtCore.QRect(180, 67, 45, 20))
        self.exp_btn_2.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn_2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_btn_2.setFont(font)
        self.exp_btn_2.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"\n"
"")
        self.exp_btn_2.setObjectName("exp_btn_2")
        self.exp_btn2_3 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn2_3.setGeometry(QtCore.QRect(230, 97, 42, 20))
        self.exp_btn2_3.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn2_3.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.exp_btn2_3.setFont(font)
        self.exp_btn2_3.setStyleSheet("background-color: rgb(255, 92, 42);\n"
"")
        self.exp_btn2_3.setObjectName("exp_btn2_3")
        self.exp_btn_3 = QtWidgets.QPushButton(self.groupBox_21)
        self.exp_btn_3.setGeometry(QtCore.QRect(180, 97, 45, 20))
        self.exp_btn_3.setMinimumSize(QtCore.QSize(25, 20))
        self.exp_btn_3.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_btn_3.setFont(font)
        self.exp_btn_3.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"\n"
"")
        self.exp_btn_3.setObjectName("exp_btn_3")
        self.exp_lbl_2 = QtWidgets.QLabel(self.groupBox_21)
        self.exp_lbl_2.setGeometry(QtCore.QRect(30, 67, 100, 20))
        self.exp_lbl_2.setMinimumSize(QtCore.QSize(20, 20))
        self.exp_lbl_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_lbl_2.setFont(font)
        self.exp_lbl_2.setObjectName("exp_lbl_2")
        self.exp_lbl_3 = QtWidgets.QLabel(self.groupBox_21)
        self.exp_lbl_3.setGeometry(QtCore.QRect(30, 97, 90, 20))
        self.exp_lbl_3.setMinimumSize(QtCore.QSize(20, 20))
        self.exp_lbl_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exp_lbl_3.setFont(font)
        self.exp_lbl_3.setObjectName("exp_lbl_3")
        self.exp_ind = QtWidgets.QLabel(self.groupBox_21)
        self.exp_ind.setGeometry(QtCore.QRect(10, 37, 15, 20))
        self.exp_ind.setMinimumSize(QtCore.QSize(10, 10))
        self.exp_ind.setMaximumSize(QtCore.QSize(125, 50))
        self.exp_ind.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.exp_ind.setText("")
        self.exp_ind.setAlignment(QtCore.Qt.AlignCenter)
        self.exp_ind.setObjectName("exp_ind")
        self.exp_ind_2 = QtWidgets.QLabel(self.groupBox_21)
        self.exp_ind_2.setGeometry(QtCore.QRect(10, 67, 15, 20))
        self.exp_ind_2.setMinimumSize(QtCore.QSize(10, 10))
        self.exp_ind_2.setMaximumSize(QtCore.QSize(125, 50))
        self.exp_ind_2.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.exp_ind_2.setText("")
        self.exp_ind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.exp_ind_2.setObjectName("exp_ind_2")
        self.exp_ind_3 = QtWidgets.QLabel(self.groupBox_21)
        self.exp_ind_3.setGeometry(QtCore.QRect(10, 97, 15, 20))
        self.exp_ind_3.setMinimumSize(QtCore.QSize(10, 10))
        self.exp_ind_3.setMaximumSize(QtCore.QSize(125, 50))
        self.exp_ind_3.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.exp_ind_3.setText("")
        self.exp_ind_3.setAlignment(QtCore.Qt.AlignCenter)
        self.exp_ind_3.setObjectName("exp_ind_3")
        self.currentexp_lbl_2 = QtWidgets.QLabel(self.groupBox_21)
        self.currentexp_lbl_2.setGeometry(QtCore.QRect(130, 17, 45, 20))
        self.currentexp_lbl_2.setMinimumSize(QtCore.QSize(20, 0))
        self.currentexp_lbl_2.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentexp_lbl_2.setFont(font)
        self.currentexp_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentexp_lbl_2.setObjectName("currentexp_lbl_2")
        self.exp_lbl_3.raise_()
        self.exp_lbl_2.raise_()
        self.exp_lbl.raise_()
        self.exp_inp.raise_()
        self.num_exp_lbl.raise_()
        self.num_exp_spn.raise_()
        self.exp_btn2.raise_()
        self.remaining_lbl2.raise_()
        self.currentexp_lbl2.raise_()
        self.currentexp_lbl.raise_()
        self.remaining_lbl.raise_()
        self.exp_prog_2.raise_()
        self.exp_btn.raise_()
        self.exp_prog.raise_()
        self.last_exposed.raise_()
        self.last_exposed_2.raise_()
        self.exp_inp_2.raise_()
        self.exp_inp_3.raise_()
        self.exp_btn2_2.raise_()
        self.exp_btn_2.raise_()
        self.exp_btn2_3.raise_()
        self.exp_btn_3.raise_()
        self.exp_ind.raise_()
        self.exp_ind_2.raise_()
        self.exp_ind_3.raise_()
        self.currentexp_lbl_2.raise_()
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_22.setGeometry(QtCore.QRect(0, 370, 275, 95))
        self.groupBox_22.setMinimumSize(QtCore.QSize(50, 50))
        self.groupBox_22.setMaximumSize(QtCore.QSize(430, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.autoguiding_btn = QtWidgets.QPushButton(self.groupBox_22)
        self.autoguiding_btn.setGeometry(QtCore.QRect(188, 30, 60, 20))
        self.autoguiding_btn.setMinimumSize(QtCore.QSize(60, 20))
        self.autoguiding_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.autoguiding_btn.setFont(font)
        self.autoguiding_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.autoguiding_btn.setObjectName("autoguiding_btn")
        self.autosave_btn = QtWidgets.QPushButton(self.groupBox_22)
        self.autosave_btn.setGeometry(QtCore.QRect(188, 60, 60, 20))
        self.autosave_btn.setMinimumSize(QtCore.QSize(60, 20))
        self.autosave_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.autosave_btn.setFont(font)
        self.autosave_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.autosave_btn.setObjectName("autosave_btn")
        self.autoguiding_lbl = QtWidgets.QLabel(self.groupBox_22)
        self.autoguiding_lbl.setGeometry(QtCore.QRect(108, 30, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.autoguiding_lbl.setFont(font)
        self.autoguiding_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoguiding_lbl.setObjectName("autoguiding_lbl")
        self.autosave_lbl = QtWidgets.QLabel(self.groupBox_22)
        self.autosave_lbl.setGeometry(QtCore.QRect(108, 60, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.autosave_lbl.setFont(font)
        self.autosave_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autosave_lbl.setObjectName("autosave_lbl")
        self.offset_btn = QtWidgets.QPushButton(self.groupBox_22)
        self.offset_btn.setGeometry(QtCore.QRect(30, 40, 60, 25))
        self.offset_btn.setMinimumSize(QtCore.QSize(60, 20))
        self.offset_btn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.offset_btn.setFont(font)
        self.offset_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.offset_btn.setObjectName("offset_btn")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_13.setGeometry(QtCore.QRect(280, 400, 150, 65))
        self.groupBox_13.setMinimumSize(QtCore.QSize(100, 50))
        self.groupBox_13.setMaximumSize(QtCore.QSize(190, 275))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.opends9_btn = QtWidgets.QPushButton(self.groupBox_13)
        self.opends9_btn.setGeometry(QtCore.QRect(40, 28, 65, 20))
        self.opends9_btn.setMinimumSize(QtCore.QSize(60, 20))
        self.opends9_btn.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.opends9_btn.setFont(font)
        self.opends9_btn.setStyleSheet("background-color: rgb(149, 254, 249);\n"
"")
        self.opends9_btn.setObjectName("opends9_btn")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FHiRE GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.claudius_lbl1.setText(_translate("MainWindow", ">>>"))
        self.claudius_lbl2.setText(_translate("MainWindow", "Send terminal commands directly to Claudius. (ex: nn2) \n"
" Terminal output displayed above."))
        self.testing_lbl.setText(_translate("MainWindow", "Testing:"))
        self.ADC_btn.setText(_translate("MainWindow", "ADC"))
        self.TCS_btn_2.setText(_translate("MainWindow", "TempCMS"))
        self.settings_lbl.setText(_translate("MainWindow", "Settings:"))
        self.guidingCam_btn.setText(_translate("MainWindow", "ZWO Camera"))
        self.monitoring_lbl.setText(_translate("MainWindow", "Monitoring:"))
        self.TCS_btn.setText(_translate("MainWindow", "TempCMS"))
        self.brightness_btn.setText(_translate("MainWindow", "Brightness"))
        self.vacuum_btn.setText(_translate("MainWindow", "Vacuum"))
        self.guiding_btn.setText(_translate("MainWindow", "Guiding"))
        self.cfocus_count.setText(_translate("MainWindow", "0"))
        self.cfocus_btn_sub.setText(_translate("MainWindow", "-"))
        self.cfocus_lbl.setText(_translate("MainWindow", "Current:"))
        self.cfocus_btn_add.setText(_translate("MainWindow", "+"))
        self.label_4.setText(_translate("MainWindow", "Focus:"))
        self.dir_inp.setPlaceholderText(_translate("MainWindow", "/home/fhire"))
        self.dir_tool_btn_2.setText(_translate("MainWindow", "..."))
        self.prefix_inp.setPlaceholderText(_translate("MainWindow", "XXX_01.fit"))
        self.prefix_lbl.setText(_translate("MainWindow", "Image Prefix:"))
        self.destin_lbl.setText(_translate("MainWindow", "Destination:"))
        self.filter_btn.setText(_translate("MainWindow", "Set"))
        self.filter_cmb.setItemText(0, _translate("MainWindow", "ND 1.8"))
        self.filter_cmb.setItemText(1, _translate("MainWindow", "ND 3.0"))
        self.filter_cmb.setItemText(2, _translate("MainWindow", "V Filter"))
        self.filter_cmb.setItemText(3, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(4, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(5, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(6, _translate("MainWindow", "Empty"))
        self.filter_cmb.setItemText(7, _translate("MainWindow", "Empty"))
        self.filter_lbl.setText(_translate("MainWindow", "Filter:"))
        self.home_rb.setText(_translate("MainWindow", "Home"))
        self.mirror_rb.setText(_translate("MainWindow", "Mirror"))
        self.splitter_rb.setText(_translate("MainWindow", "Splitter"))
        self.stage_lbl.setText(_translate("MainWindow", "Stage:"))
        self.exp_lbl.setText(_translate("MainWindow", "Guiding Camera:"))
        self.num_exp_lbl.setText(_translate("MainWindow", "# Exp:"))
        self.exp_btn2.setText(_translate("MainWindow", "Abort"))
        self.remaining_lbl2.setText(_translate("MainWindow", "56s"))
        self.currentexp_lbl2.setText(_translate("MainWindow", "1"))
        self.currentexp_lbl.setText(_translate("MainWindow", "Current \n"
"Exp:"))
        self.remaining_lbl.setText(_translate("MainWindow", "Remaining \n"
"Time:"))
        self.exp_prog_2.setFormat(_translate("MainWindow", "%ps"))
        self.exp_btn.setText(_translate("MainWindow", "Expose"))
        self.exp_prog.setFormat(_translate("MainWindow", "%ps"))
        self.last_exposed.setText(_translate("MainWindow", "Last Exposed:"))
        self.last_exposed_2.setText(_translate("MainWindow", "---------------------"))
        self.exp_btn2_2.setText(_translate("MainWindow", "Abort"))
        self.exp_btn_2.setText(_translate("MainWindow", "Expose"))
        self.exp_btn2_3.setText(_translate("MainWindow", "Abort"))
        self.exp_btn_3.setText(_translate("MainWindow", "Expose"))
        self.exp_lbl_2.setText(_translate("MainWindow", "Refractor Camera:"))
        self.exp_lbl_3.setText(_translate("MainWindow", "Spectrograph:"))
        self.currentexp_lbl_2.setText(_translate("MainWindow", "Exp. (s)"))
        self.autoguiding_btn.setText(_translate("MainWindow", "ON"))
        self.autosave_btn.setText(_translate("MainWindow", "ON"))
        self.autoguiding_lbl.setText(_translate("MainWindow", "Autoguiding:"))
        self.autosave_lbl.setText(_translate("MainWindow", "Autosave:"))
        self.offset_btn.setText(_translate("MainWindow", "OFFSET"))
        self.opends9_btn.setText(_translate("MainWindow", "Open DS9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
