# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1036, 356)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.turboBox = QtGui.QGroupBox(self.centralwidget)
        self.turboBox.setMinimumSize(QtCore.QSize(250, 60))
        self.turboBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.turboBox.setObjectName(_fromUtf8("turboBox"))
        self.turbo_switch = QtGui.QPushButton(self.turboBox)
        self.turbo_switch.setGeometry(QtCore.QRect(0, 30, 99, 27))
        self.turbo_switch.setText(_fromUtf8(""))
        self.turbo_switch.setObjectName(_fromUtf8("turbo_switch"))
        self.gridLayout.addWidget(self.turboBox, 1, 2, 1, 1)
        self.pump_button_off = QtGui.QPushButton(self.centralwidget)
        self.pump_button_off.setObjectName(_fromUtf8("pump_button_off"))
        self.gridLayout.addWidget(self.pump_button_off, 3, 1, 1, 1)
        self.pump_button_on = QtGui.QPushButton(self.centralwidget)
        self.pump_button_on.setObjectName(_fromUtf8("pump_button_on"))
        self.gridLayout.addWidget(self.pump_button_on, 2, 1, 1, 1)
        self.ion_button_on = QtGui.QPushButton(self.centralwidget)
        self.ion_button_on.setObjectName(_fromUtf8("ion_button_on"))
        self.gridLayout.addWidget(self.ion_button_on, 2, 3, 1, 1)
        self.ion_button_off = QtGui.QPushButton(self.centralwidget)
        self.ion_button_off.setObjectName(_fromUtf8("ion_button_off"))
        self.gridLayout.addWidget(self.ion_button_off, 3, 3, 1, 1)
        self.turbo_button_off = QtGui.QPushButton(self.centralwidget)
        self.turbo_button_off.setObjectName(_fromUtf8("turbo_button_off"))
        self.gridLayout.addWidget(self.turbo_button_off, 3, 2, 1, 1)
        self.pump_down = QtGui.QPushButton(self.centralwidget)
        self.pump_down.setObjectName(_fromUtf8("pump_down"))
        self.gridLayout.addWidget(self.pump_down, 4, 1, 1, 1)
        self.backingBox = QtGui.QGroupBox(self.centralwidget)
        self.backingBox.setMinimumSize(QtCore.QSize(250, 60))
        self.backingBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.backingBox.setObjectName(_fromUtf8("backingBox"))
        self.backing_switch = QtGui.QPushButton(self.backingBox)
        self.backing_switch.setGeometry(QtCore.QRect(0, 30, 99, 27))
        self.backing_switch.setText(_fromUtf8(""))
        self.backing_switch.setObjectName(_fromUtf8("backing_switch"))
        self.gridLayout.addWidget(self.backingBox, 1, 1, 1, 1)
        self.abort_pump_down = QtGui.QPushButton(self.centralwidget)
        self.abort_pump_down.setObjectName(_fromUtf8("abort_pump_down"))
        self.gridLayout.addWidget(self.abort_pump_down, 4, 2, 1, 1)
        self.tic_pressure_box = QtGui.QGroupBox(self.centralwidget)
        self.tic_pressure_box.setObjectName(_fromUtf8("tic_pressure_box"))
        self.tic_pressureText = QtGui.QLineEdit(self.tic_pressure_box)
        self.tic_pressureText.setGeometry(QtCore.QRect(0, 30, 251, 27))
        self.tic_pressureText.setReadOnly(True)
        self.tic_pressureText.setObjectName(_fromUtf8("tic_pressureText"))
        self.gridLayout.addWidget(self.tic_pressure_box, 6, 3, 2, 1)
        self.stop_plot = QtGui.QPushButton(self.centralwidget)
        self.stop_plot.setObjectName(_fromUtf8("stop_plot"))
        self.gridLayout.addWidget(self.stop_plot, 7, 2, 1, 1)
        self.vent = QtGui.QPushButton(self.centralwidget)
        self.vent.setObjectName(_fromUtf8("vent"))
        self.gridLayout.addWidget(self.vent, 4, 3, 1, 1)
        self.gauge_button = QtGui.QPushButton(self.centralwidget)
        self.gauge_button.setObjectName(_fromUtf8("gauge_button"))
        self.gridLayout.addWidget(self.gauge_button, 6, 1, 1, 1)
        self.auto_plot = QtGui.QPushButton(self.centralwidget)
        self.auto_plot.setObjectName(_fromUtf8("auto_plot"))
        self.gridLayout.addWidget(self.auto_plot, 7, 1, 1, 1)
        self.graph = QtGui.QPushButton(self.centralwidget)
        self.graph.setObjectName(_fromUtf8("graph"))
        self.gridLayout.addWidget(self.graph, 6, 2, 1, 1)
        self.negBox = QtGui.QGroupBox(self.centralwidget)
        self.negBox.setMinimumSize(QtCore.QSize(250, 60))
        self.negBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.negBox.setObjectName(_fromUtf8("negBox"))
        self.neg_switch = QtGui.QPushButton(self.negBox)
        self.neg_switch.setGeometry(QtCore.QRect(0, 30, 99, 27))
        self.neg_switch.setText(_fromUtf8(""))
        self.neg_switch.setObjectName(_fromUtf8("neg_switch"))
        self.gridLayout.addWidget(self.negBox, 1, 4, 1, 1)
        self.neg_button_off = QtGui.QPushButton(self.centralwidget)
        self.neg_button_off.setObjectName(_fromUtf8("neg_button_off"))
        self.gridLayout.addWidget(self.neg_button_off, 3, 4, 1, 1)
        self.neg_button_on = QtGui.QPushButton(self.centralwidget)
        self.neg_button_on.setObjectName(_fromUtf8("neg_button_on"))
        self.gridLayout.addWidget(self.neg_button_on, 2, 4, 1, 1)
        self.ionBox = QtGui.QGroupBox(self.centralwidget)
        self.ionBox.setMinimumSize(QtCore.QSize(250, 60))
        self.ionBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.ionBox.setObjectName(_fromUtf8("ionBox"))
        self.ion_switch = QtGui.QPushButton(self.ionBox)
        self.ion_switch.setGeometry(QtCore.QRect(0, 30, 99, 27))
        self.ion_switch.setText(_fromUtf8(""))
        self.ion_switch.setObjectName(_fromUtf8("ion_switch"))
        self.gridLayout.addWidget(self.ionBox, 1, 3, 1, 1)
        self.turbo_button_on = QtGui.QPushButton(self.centralwidget)
        self.turbo_button_on.setObjectName(_fromUtf8("turbo_button_on"))
        self.gridLayout.addWidget(self.turbo_button_on, 2, 2, 1, 1)
        self.ion_pressure_box = QtGui.QGroupBox(self.centralwidget)
        self.ion_pressure_box.setObjectName(_fromUtf8("ion_pressure_box"))
        self.ion_pressureText = QtGui.QLineEdit(self.ion_pressure_box)
        self.ion_pressureText.setGeometry(QtCore.QRect(0, 30, 251, 27))
        self.ion_pressureText.setReadOnly(True)
        self.ion_pressureText.setObjectName(_fromUtf8("ion_pressureText"))
        self.gridLayout.addWidget(self.ion_pressure_box, 6, 4, 2, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(120, 60))
        self.textEdit.setMaximumSize(QtCore.QSize(2000, 30))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 8, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuOptions.addAction(self.actionImport)
        self.menuOptions.addAction(self.actionExit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FHiRE Vacuum Controller", None))
        self.turboBox.setTitle(_translate("MainWindow", "Turbo Pump", None))
        self.pump_button_off.setText(_translate("MainWindow", "Backing Pump Off", None))
        self.pump_button_on.setText(_translate("MainWindow", "Backing Pump On", None))
        self.ion_button_on.setText(_translate("MainWindow", "Ion Pump On", None))
        self.ion_button_off.setText(_translate("MainWindow", "Ion Pump Off", None))
        self.turbo_button_off.setText(_translate("MainWindow", "Turbo Pump Off", None))
        self.pump_down.setText(_translate("MainWindow", "Pump Down", None))
        self.backingBox.setTitle(_translate("MainWindow", "Backing Pump", None))
        self.abort_pump_down.setText(_translate("MainWindow", "Abort Pump Down", None))
        self.tic_pressure_box.setTitle(_translate("MainWindow", "TIC Gauge Pressure:", None))
        self.stop_plot.setText(_translate("MainWindow", "Stop AutoPlotting", None))
        self.vent.setText(_translate("MainWindow", "Vent", None))
        self.gauge_button.setText(_translate("MainWindow", "Read Gauge", None))
        self.auto_plot.setText(_translate("MainWindow", "Auto Plot", None))
        self.graph.setText(_translate("MainWindow", "Manual Graph", None))
        self.negBox.setTitle(_translate("MainWindow", "NEG Pump", None))
        self.neg_button_off.setText(_translate("MainWindow", "Neg Pump Off", None))
        self.neg_button_on.setText(_translate("MainWindow", "Neg Pump On", None))
        self.ionBox.setTitle(_translate("MainWindow", "Ion Pump", None))
        self.turbo_button_on.setText(_translate("MainWindow", "Turbo Pump On", None))
        self.ion_pressure_box.setTitle(_translate("MainWindow", "Ion Pump Pressure:", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.actionImport.setText(_translate("MainWindow", "Import Pressure Log", None))
        self.actionExit.setText(_translate("MainWindow", "Quit", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vacuum = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(vacuum)
    vacuum.show()
    sys.exit(app.exec_())

